import { DocumentItem } from '../types';

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-rag-foundational-paper',
    title: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks (Lewis et al. 2020)',
    category: 'research',
    institution: 'General AI',
    summary: 'The seminal academic research paper defining RAG, Dense Passage Retrieval (DPR), Marginalization over latent documents, and hallucination reduction.',
    fileType: 'md',
    pageCount: 6,
    wordCount: 1350,
    charCount: 8900,
    dateAdded: '2020-05-22',
    chunks: [],
    content: `# Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks
## Patrick Lewis, Ethan Perez, Aleksandros Piktus, Fabio Petroni, Vladimir Karpukhin, Barlas Oğuz, Heinrich Küttler, Mike Lewis, Wen-tau Yih, Tim Rocktäschel, Sebastian Riedel, Douwe Kiela
### NeurIPS 2020 / Facebook AI Research (FAIR), UCL, NYU

### Abstract & Core Innovation
Large pre-trained language models store factual knowledge in their implicit parameters (parametric memory). However, parametric memory suffers from severe limitations:
1. Inability to precisely expand or revise memory without expensive full re-training.
2. Inability to provide direct provenance and verifiable citations for generated answers.
3. Susceptibility to catastrophic hallucinations and factual confabulations.

To solve this, we introduce **Retrieval-Augmented Generation (RAG)**: a hybrid neural framework combining a pre-trained parametric sequence-to-sequence generator (e.g., BART) with a non-parametric dense retrieval index (Dense Passage Retrieval / DPR) over Wikipedia.

### 1. Mathematical Architecture & Formulations
RAG models use the input query $x$ to retrieve top-$K$ latent document passages $z \\in \\text{top-}K(p_\\eta(\\cdot|x))$, and treat the retrieved passages as latent variables conditioned upon by the generator $p_\\theta(y_i|x, z, y_{1:i-1})$.

Two distinct formulation variants are proposed:
- **RAG-Sequence Model:** The retriever draws top-$K$ documents, and the generator produces the entire output sequence conditioned on the same document $z$:
  $$p_{\\text{RAG-Seq}}(y|x) \\approx \\sum_{z \\in \\text{top-}K(p(\\cdot|x))} p_\\eta(z|x) \\prod_{i=1}^N p_\\theta(y_i|x, z, y_{1:i-1})$$
- **RAG-Token Model:** The retriever allows different retrieved passages to guide the generation of each subsequent token $y_i$:
  $$p_{\\text{RAG-Token}}(y|x) \\approx \\prod_{i=1}^N \\sum_{z \\in \\text{top-}K(p(\\cdot|x))} p_\\eta(z|x) p_\\theta(y_i|x, z, y_{1:i-1})$$

### 2. Dense Passage Retrieval (DPR) Component
The retriever calculates similarity using dense embeddings generated by dual BERT bi-encoders:
$$p_\\eta(z|x) \\propto \\exp(\\mathbf{d}(z)^\\top \\mathbf{q}(x))$$
where $\\mathbf{q}(x) = \\text{BERT}_Q(x)$ is a 768-dimensional query representation and $\\mathbf{d}(z) = \\text{BERT}_D(z)$ is the passage representation. Fast nearest-neighbor lookup is conducted using Inverted File Index with Vector Quantization (FAISS / HNSW).

### 3. Key Findings & Empirical Benchmarks
- On open-domain question answering datasets (Natural Questions, WebQuestions, CuratedTREC), RAG set new state-of-the-art results outperforming pure parametric models (T5-11B) despite having significantly fewer parameters.
- **Factual Accuracy & Hallucination Mitigation:** Human evaluation demonstrated that RAG generates significantly more factual, grounded, and specific responses compared to standard generative language models.
- **Knowledge Updateability:** By simply updating the non-parametric document index without retraining the generator parameters, the system successfully adapts to changing world knowledge instantly.`,
  },
];
