import { DocumentItem } from '../types';

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-rag-foundational-paper',
    title: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks (Lewis et al. 2020)',
    category: 'research',
    institution: 'RAG Research',
    summary: 'Seminal research paper defining RAG-Sequence and RAG-Token models, Dense Passage Retrieval (DPR), Marginalization over latent passages, and hallucination reduction.',
    fileType: 'md',
    pageCount: 6,
    wordCount: 920,
    charCount: 6200,
    dateAdded: '2020-05-22',
    chunks: [],
    content: `# Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks
## Patrick Lewis, Ethan Perez, Aleksandros Piktus, Fabio Petroni, Vladimir Karpukhin et al. (NeurIPS 2020 / FAIR, UCL, NYU)

### 1. Abstract & Core Innovation
Large pre-trained language models store factual knowledge in their implicit parameters (parametric memory). However, parametric memory suffers from severe limitations:
1. Inability to precisely expand or revise memory without expensive full re-training.
2. Inability to provide direct provenance and verifiable citations for generated answers.
3. Susceptibility to catastrophic hallucinations and factual confabulations.

To solve this, we introduce **Retrieval-Augmented Generation (RAG)**: a hybrid neural framework combining a pre-trained parametric sequence-to-sequence generator (e.g., BART) with a non-parametric dense retrieval index (Dense Passage Retrieval / DPR) over document collections.

### 2. Mathematical Formulations
RAG models use the input query $x$ to retrieve top-$K$ latent document passages $z \\in \\text{top-}K(p_\\eta(\\cdot|x))$, and treat the retrieved passages as latent variables conditioned upon by the generator $p_\\theta(y_i|x, z, y_{1:i-1})$.

- **RAG-Sequence Model:** The retriever draws top-$K$ documents, and the generator produces the entire output sequence conditioned on the same document $z$:
  $$p_{\\text{RAG-Seq}}(y|x) \\approx \\sum_{z \\in \\text{top-}K(p(\\cdot|x))} p_\\eta(z|x) \\prod_{i=1}^N p_\\theta(y_i|x, z, y_{1:i-1})$$
- **RAG-Token Model:** The retriever allows different retrieved passages to guide the generation of each subsequent token $y_i$:
  $$p_{\\text{RAG-Token}}(y|x) \\approx \\prod_{i=1}^N \\sum_{z \\in \\text{top-}K(p(\\cdot|x))} p_\\eta(z|x) p_\\theta(y_i|x, z, y_{1:i-1})$$

### 3. Dense Passage Retrieval (DPR) & Vector Search
The retriever calculates similarity using dense embeddings generated by dual BERT bi-encoders:
$$p_\\eta(z|x) \\propto \\exp(\\mathbf{d}(z)^\\top \\mathbf{q}(x))$$
where $\\mathbf{q}(x)$ is a 768-dimensional query representation and $\\mathbf{d}(z)$ is the passage representation. Fast nearest-neighbor lookup is conducted using Inverted File Index with Vector Quantization (FAISS / HNSW).

### 4. Key Findings & Empirical Benchmarks
- On open-domain question answering datasets (Natural Questions, WebQuestions, CuratedTREC), RAG set new state-of-the-art results outperforming pure parametric models (T5-11B) despite having significantly fewer parameters.
- **Hallucination Mitigation:** Human evaluation demonstrated that RAG generates significantly more factual, grounded, and specific responses compared to standard generative language models.`,
  },
  {
    id: 'doc-transformers-deep-learning',
    title: 'Attention Is All You Need: Transformer Architectures & Deep Learning (Vaswani et al.)',
    category: 'technical',
    institution: 'AI & Deep Learning',
    summary: 'Foundational architecture of modern Large Language Models based on Scaled Dot-Product Attention, Multi-Head Attention mechanisms, and Positional Encodings.',
    fileType: 'md',
    pageCount: 5,
    wordCount: 880,
    charCount: 5900,
    dateAdded: '2017-06-12',
    chunks: [],
    content: `# Attention Is All You Need: Transformer Architectures & Deep Learning
## Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit, Llion Jones, Aidan N. Gomez, Łukasz Kaiser, Illia Polosukhin (NeurIPS 2017 / Google Brain & Google Research)

### 1. Architectural Overview & Motivation
The dominant sequence transduction models prior to Transformers were based on complex recurrent (RNN, LSTM, GRU) or convolutional neural networks. Recurrent models inherently factor computation along the symbol positions of the input and output sequences, precluding parallelization within training examples.

The **Transformer** eliminates recurrence entirely and relies solely on attention mechanisms to draw global dependencies between input and output tokens.

### 2. Scaled Dot-Product Attention
The fundamental building block is Scaled Dot-Product Attention. Given queries $Q$, keys $K$ of dimension $d_k$, and values $V$ of dimension $d_v$:
$$\\text{Attention}(Q, K, V) = \\text{softmax}\\left(\\frac{QK^T}{\\sqrt{d_k}}\\right)V$$
The scaling factor $\\frac{1}{\\sqrt{d_k}}$ is critical: for large values of $d_k$, the dot products grow large in magnitude, pushing the softmax function into regions with extremely small gradients.

### 3. Multi-Head Attention (MHA)
Instead of performing a single attention function with $d_{\\text{model}}$-dimensional queries, keys, and values, Multi-Head Attention linearly projects queries, keys, and values $h$ times with different, learned linear projections to $d_k, d_k,$ and $d_v$ dimensions:
$$\\text{MultiHead}(Q, K, V) = \\text{Concat}(\\text{head}_1, \\dots, \\text{head}_h)W^O$$
$$\\text{where } \\text{head}_i = \\text{Attention}(QW_i^Q, KW_i^K, VW_i^V)$$
This allows the model to jointly attend to information from different representation subspaces at different positions.

### 4. Positional Encodings & Feed-Forward Networks
Because the model contains no recurrence and no convolution, it injects token position information using sinusoidal functions of varying frequencies:
$$PE_{(pos, 2i)} = \\sin(pos / 10000^{2i/d_{\\text{model}}})$$
$$PE_{(pos, 2i+1)} = \\cos(pos / 10000^{2i/d_{\\text{model}}})$$
Each sub-layer is augmented with residual connections followed by Layer Normalization: $\\text{LayerNorm}(x + \\text{Sublayer}(x))$.`,
  },
  {
    id: 'doc-ml-foundations-loss',
    title: 'Machine Learning Foundations: Optimization, Loss Functions & Regularization',
    category: 'technical',
    institution: 'Machine Learning',
    summary: 'Comprehensive mathematical treatise on statistical learning theory, empirical risk minimization, gradient descent optimization (AdamW), and the bias-variance tradeoff.',
    fileType: 'md',
    pageCount: 5,
    wordCount: 840,
    charCount: 5600,
    dateAdded: '2023-01-15',
    chunks: [],
    content: `# Machine Learning Foundations: Optimization, Loss Functions & Regularization
## Technical Engineering Guide & Theoretical Foundations

### 1. Empirical Risk Minimization & Loss Functions
In supervised machine learning, given a dataset $\\mathcal{D} = \\{(x_i, y_i)\\}_{i=1}^N$, we seek parameters $\\theta^*$ that minimize the expected loss:
$$\\theta^* = \\arg\\min_\\theta \\frac{1}{N} \\sum_{i=1}^N \\mathcal{L}(f_\\theta(x_i), y_i) + \\lambda \\mathcal{R}(\\theta)$$

Common objective formulations:
- **Cross-Entropy Loss (Classification):**
  $$\\mathcal{L}_{\\text{CE}} = -\\sum_{k=1}^C y_k \\log(\\hat{y}_k) = -\\log\\left(\\frac{e^{z_{\\text{true}}}}{\\sum_j e^{z_j}}\\right)$$
- **Mean Squared Error (Regression):**
  $$\\mathcal{L}_{\\text{MSE}} = \\frac{1}{N}\\sum_{i=1}^N (y_i - \\hat{y}_i)^2$$

### 2. The Bias-Variance Decomposition
For an estimator $\\hat{f}(x)$, the expected generalization error decomposes mathematically into three distinct components:
$$\\mathbb{E}[(y - \\hat{f}(x))^2] = \\text{Bias}[\\hat{f}(x)]^2 + \\text{Var}[\\hat{f}(x)] + \\sigma_{\\text{irreducible}}^2$$
- **High Bias (Underfitting):** The model makes strong simplifying assumptions and fails to capture data complexity.
- **High Variance (Overfitting):** The model is excessively sensitive to training set fluctuations and noise.

### 3. Gradient Optimization & Adaptive Methods (AdamW)
Gradient Descent updates parameters along the negative gradient: $\\theta_{t+1} = \\theta_t - \\eta \\nabla_\\theta \\mathcal{L}$.
Modern deep learning predominantly uses **AdamW (Adaptive Moment Estimation with Decoupled Weight Decay)**:
1. First moment estimate: $m_t = \\beta_1 m_{t-1} + (1 - \\beta_1) g_t$
2. Second moment estimate: $v_t = \\beta_2 v_{t-1} + (1 - \\beta_2) g_t^2$
3. Bias correction: $\\hat{m}_t = \\frac{m_t}{1 - \\beta_1^t}, \\quad \\hat{v}_t = \\frac{v_t}{1 - \\beta_2^t}$
4. Parameter update with decoupled weight decay: $\\theta_{t+1} = \\theta_t - \\eta \\left( \\frac{\\hat{m}_t}{\\sqrt{\\hat{v}_t} + \\epsilon} + \\lambda \\theta_t \\right)$

### 4. Regularization Techniques
- **L2 Regularization (Ridge / Weight Decay):** Adds penalty $\\frac{1}{2}\\lambda \\|\\theta\\|_2^2$ to shrink weights toward zero.
- **L1 Regularization (Lasso):** Adds penalty $\\lambda \\|\\theta\\|_1$ promoting sparsity in parameter space.
- **Dropout:** Randomly deactivates activations during training with probability $p$ to prevent co-adaptation.`,
  },
  {
    id: 'doc-data-science-statistics',
    title: 'Data Science: Statistical Inference, Dimensionality Reduction & PCA',
    category: 'academic',
    institution: 'Data Science',
    summary: 'Core statistical learning principles including Principal Component Analysis (PCA), Covariance Eigendecomposition, Singular Value Decomposition (SVD), and Hypothesis Testing.',
    fileType: 'md',
    pageCount: 5,
    wordCount: 860,
    charCount: 5750,
    dateAdded: '2023-04-10',
    chunks: [],
    content: `# Data Science: Statistical Inference, Dimensionality Reduction & PCA
## Advanced Analytical Methods & Statistical Foundations

### 1. Principal Component Analysis (PCA) Derivation
Principal Component Analysis is an unsupervised linear transformation that projects data from high-dimensional space $\\mathbb{R}^D$ into lower-dimensional space $\\mathbb{R}^K$ ($K < D$) while maximizing variance.

Given zero-centered data matrix $X \\in \\mathbb{R}^{N \\times D}$, the sample covariance matrix $\\Sigma$ is:
$$\\Sigma = \\frac{1}{N-1} X^T X$$
We seek projection vector $w_1$ maximizing variance:
$$\\max_{w_1} w_1^T \\Sigma w_1 \\quad \\text{subject to } w_1^T w_1 = 1$$
Using the Lagrange multiplier $\\mathcal{L}(w_1, \\lambda) = w_1^T \\Sigma w_1 - \\lambda (w_1^T w_1 - 1)$, taking the derivative yields the characteristic **Eigenvalue Equation**:
$$\\Sigma w_1 = \\lambda w_1$$
The principal components are the eigenvectors of $\\Sigma$ sorted in descending order of their eigenvalues $\\lambda_1 \\ge \\lambda_2 \\ge \\dots \\ge \\lambda_D$.

### 2. Singular Value Decomposition (SVD)
Any real matrix $X \\in \\mathbb{R}^{N \\times D}$ can be factored into:
$$X = U \\Sigma V^T$$
where $U \\in \\mathbb{R}^{N \\times N}$ and $V \\in \\mathbb{R}^{D \\times D}$ are orthogonal matrices containing left-singular and right-singular vectors, and $\\Sigma$ is a diagonal matrix containing singular values $\\sigma_i = \\sqrt{\\lambda_i}$.

### 3. Statistical Hypothesis Testing & Significance
- **Null Hypothesis ($H_0$):** Assumes no effect or no difference between sample distributions.
- **p-value:** The probability of observing test results at least as extreme as the observed data, assuming $H_0$ is true.
- **Type I Error ($\\alpha$):** False Positive (rejecting true $H_0$). Controlled by significance threshold (typically $\\alpha = 0.05$).
- **Type II Error ($\\beta$):** False Negative (failing to reject false $H_0$). Statistical Power is $1 - \\beta$.`,
  },
  {
    id: 'doc-nlp-vector-search',
    title: 'Dense Vector Embeddings, Metric Spaces & Vector Search Indexing (HNSW / FAISS)',
    category: 'technical',
    institution: 'NLP & Embeddings',
    summary: 'Algorithmic guide on converting text into dense metric spaces, cosine similarity geometry on unit hyperspheres, and sub-linear ANN search with HNSW graphs.',
    fileType: 'md',
    pageCount: 5,
    wordCount: 890,
    charCount: 6000,
    dateAdded: '2023-09-18',
    chunks: [],
    content: `# Dense Vector Embeddings, Metric Spaces & Vector Search Indexing
## Algorithmic Engineering for Information Retrieval & Similarity Search

### 1. Vector Embeddings & Metric Geometry
A vector embedding model $f: \\mathcal{X} \\to \\mathbb{R}^D$ maps natural language tokens or passages into a continuous $D$-dimensional metric space where semantic proximity corresponds to geometric distance.

- **Dot Product:** $\\langle u, v \\rangle = \\sum_{i=1}^D u_i v_i$
- **Cosine Similarity:**
  $$\\cos(\\theta) = \\frac{u \\cdot v}{\\|u\\|_2 \\|v\\|_2} = \\frac{\\sum_{i=1}^D u_i v_i}{\\sqrt{\\sum_{i=1}^D u_i^2} \\sqrt{\\sum_{i=1}^D v_i^2}}$$
- **L2 (Euclidean) Distance on Unit Hypersphere $\\mathbb{S}^{D-1}$:**
  When vectors are normalized such that $\\|u\\|_2 = \\|v\\|_2 = 1$:
  $$\\|u - v\\|_2^2 = \\|u\\|_2^2 + \\|v\\|_2^2 - 2(u \\cdot v) = 2 - 2\\cos(\\theta)$$
  Thus, maximizing cosine similarity is strictly equivalent to minimizing Euclidean distance on the unit sphere.

### 2. Approximate Nearest Neighbor (ANN) Algorithms
Exhaustive linear search $O(N \\cdot D)$ is intractable for millions of chunks. Modern vector databases use sub-linear ANN structures:

1. **Inverted File with Product Quantization (IVF-PQ):**
   - Partitions vector space into Voronoi cells using k-means clustering.
   - Compresses vectors into compact byte codes by quantizing sub-vectors, yielding $10\\times-50\\times$ memory reduction.
2. **Hierarchical Navigable Small World (HNSW):**
   - Multi-layer graph structure inspired by skip-lists.
   - Top layers feature long-range connections for rapid coarse routing; bottom layers feature dense local connections for high-recall nearest neighbor discovery.
   - Achieves logarithmic search complexity: $O(\\log N)$.

### 3. Hybrid Search: Dense + Sparse Fusion (BM25 + Dense)
Dense vectors excel at semantic generalization (synonyms, paraphrase), but struggle with rare keywords, exact serial numbers, and acronyms.
**Reciprocal Rank Fusion (RRF)** unifies both rankings:
$$\\text{RRF\\_Score}(d) = \\sum_{m \\in \\{Dense, BM25\\}} \\frac{1}{k + \\text{rank}_m(d)}$$
where $k \\approx 60$ acts as a smoothing parameter to balance dense and lexical contributions robustly.`,
  },
];
